language: python
python:
- '3.7'

install:
- pip install -r requirements.txt
script:
- make publish
deploy:
  provider: pages
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: writing
